#!/usr/bin/zsh

dbus-send --session --type=method_call --print-reply=literal --dest=org.gnome.Shell /org/gnome/Shell/Extensions/IbusSwitcher org.gnome.Shell.Extensions.IbusSwitcher.SwitchSource uint32:${origin_im_status[index]} string:${origin_im_status[mode]} > /dev/null